### ISSUE TITLE
Track files read with/written by built-in libraries

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#111]
Built-in libraries like `codecs` and `json`. 

Robin's comment on Slack: 
I've worked out what the problem with `codecs` was. You were right: it is because of the way that it is provided as a 'built-in library' (note: this is different to a 'built-in function' like `open`). Some (most? all?) of the libraries that are actually provided with Python (such as `sys`, `os`...and `codecs`) are actually semi-loaded by default when you open the Python interpreter. That sounds weird, but basically loading a module in Python consists of two steps:

1. The module name is 'searched for', and eventually the right .py file containing the module is found, and the module is loaded and put into `sys.modules` (which is just a dict with keys of module names, and values of the `Module` object itself). This is the bit that recipy hooks into, and it alters the module before it gets into the `sys.modules` dict.

2. The module is added to the 'global scope' so that you can access it by using its name.

When you run something like `import numpy`, then both of these steps are run, ​_but_​ when you run `import codecs` then it finds that codecs already exists in the `sys.modules` dict, and so it doesn't do step 1 (it is already 'found' and 'loaded'), it just has to make it available in the current scope (basically it does `codecs = sys.modules['codecs']`).

The result of all of this is that it doesn't work automatically with recipy at the moment, because recipy has to catch it ​_before_​ it goes into `sys.modules` - but it is in there as soon as you start the Python interpreter! The way to make it work is to add these two lines at the beginning of the script:

```import sys

del sys.modules['codecs']```

which removes it from `sys.modules`, so that when `import codecs` is called, it goes through both steps above and recipy has a chance to patch it.

I've pushed a commit to the `patchCodecs` branch which adds those two lines and shows that it works.

The key question is what we do about this going forward....I'm not sure what is best. We could automatically run the `del sys.modules[MODULENAME]` for any 'built-in module' that we patch, but there could be some nasty side-effects from this (though I guess we never know til we try...!).

Hope this all made sense - any thoughts?

http://www.dabeaz.com/modulepackage/ModulePackage.pdf This presentation covers all of the crazy nuts and bolts of importing in Python - and may well help with our `codecs` problem

**Comment by jvdzwaan** [comment]
If you delete `codecs` from the `sys.modules` and then import `pandas`, pandas starts complaining: 

```
(recipy)jvdzwaan@esciencelt018:~/code/recipy-demo$ python example_script.py 
recipy run inserted, with ID 8ee5c13c-6b0c-412d-9a56-5d06702b72d0
Patching numpy
Patching input function: genfromtxt
Patching input function: loadtxt
Patching input function: fromfile
Patching output function: save
Patching output function: savez
Patching output function: savez_compressed
Patching output function: savetxt
Patching codecs
Patching input function: open
Logging exception incompatible codecs in module "encodings.unicode_escape" (/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/unicode_escape.py)
Traceback (most recent call last):
  File "example_script.py", line 2, in <module>
    import pandas as pd
  File "/home/jvdzwaan/code/recipy/recipy/PatchImporter.py", line 43, in load_module
    mod = imp.load_module(name, file_obj, pathname, desc)
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/__init__.py", line 37, in <module>
    import pandas.core.config_init
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/core/config_init.py", line 17, in <module>
    from pandas.core.format import detect_console_encoding
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/core/format.py", line 20, in <module>
    from pandas.tseries.index import DatetimeIndex
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/tseries/index.py", line 135, in <module>
    Int64Index):
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/tseries/index.py", line 811, in DatetimeIndex
    def _format_native_types(self, na_rep=u('NaT'),
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/pandas/compat/__init__.py", line 248, in u
    return unicode(s, "unicode_escape")
  File "/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/__init__.py", line 134, in search_function
    (mod.__name__, mod.__file__)
encodings.CodecRegistryError: incompatible codecs in module "encodings.unicode_escape" (/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/unicode_escape.py)
```

This has something to do with the order in which libraries are imported, so if you import `pandas` before deleting `codecs` from `sys.modules`, it works.

**Comment by jvdzwaan** [comment]
But then `matplotlib.pyplot.savefig` starts complaining with a different error message: 

```
(recipy)jvdzwaan@esciencelt018:~/code/recipy-demo$ python example_script.py 
Patching numpy
Patching input function: genfromtxt
Patching input function: loadtxt
Patching input function: fromfile
Patching output function: save
Patching output function: savez
Patching output function: savez_compressed
Patching output function: savetxt
Patching pandas
Patching input function: read_csv
Patching input function: read_table
Patching input function: read_excel
Patching input function: read_hdf
Patching input function: read_pickle
Patching input function: read_stata
Patching input function: read_msgpack
Patching output function: DataFrame.to_csv
Patching output function: DataFrame.to_excel
Patching output function: DataFrame.to_hdf
Patching output function: DataFrame.to_msgpack
Patching output function: DataFrame.to_stata
Patching output function: DataFrame.to_pickle
Patching output function: Panel.to_excel
Patching output function: Panel.to_hdf
Patching output function: Panel.to_msgpack
Patching output function: Panel.to_pickle
Patching output function: Series.to_csv
Patching output function: Series.to_hdf
Patching output function: Series.to_msgpack
Patching output function: Series.to_pickle
recipy run inserted, with ID 61c46967-968a-4cbd-a94f-9d7b26b75876
Patching matplotlib.pyplot
Patching output function: savefig
Input from /home/jvdzwaan/code/recipy-demo/data.csv using pandas
Output to /home/jvdzwaan/code/recipy-demo/newplot.pdf using matplotlib
Patching codecs
Patching input function: open
Logging exception incompatible codecs in module "encodings.mac_roman" (/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/mac_roman.py)
Traceback (most recent call last):
  File "example_script.py", line 10, in <module>
    savefig('newplot.pdf')
  File "/home/jvdzwaan/code/recipy/recipyCommon/utils.py", line 49, in f
    return wrapped(*args, **kwargs)
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2542, in print_pdf
    file.close()
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 547, in close
    self.writeFonts()
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 650, in writeFonts
    fonts[Fx] = self.embedTTF(realpath, chars[1])
  File "/home/jvdzwaan/.virtualenvs/recipy/local/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 1071, in embedTTF
    ps_name = sfnt[(1, 0, 0, 6)].decode('macroman')  # Macintosh scheme
  File "/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/__init__.py", line 134, in search_function
    (mod.__name__, mod.__file__)
encodings.CodecRegistryError: incompatible codecs in module "encodings.mac_roman" (/home/jvdzwaan/.virtualenvs/recipy/lib/python2.7/encodings/mac_roman.py)

```
Which you cant't fix by importing `matplotlib` before deleting `codecs`.

The reason I use (and want to patch) codecs is that it fixes reading utf-8 encoded files in Python 2.7. Perhaps it is better to try and find another solution. I'm thinking again about making a `recipy.open` (see also #44).

What do you think? Any other ideas?

**Comment by robintw** [comment]
Once you've run `del sys.modules['codecs']` are then importing `codecs` again manually before importing `pandas` etc? (ie. running `import codecs`) If not, then try that - that _theoretically_ should look no different to things like pandas and matplotlib!

**Comment by jvdzwaan** [comment]
Apparently it does look different to pandas and matplotlib! It only works if you import `pandas` before deleting and then importing `codecs`. And then it crashes on the `savefig`. It doesn't really make sense. I'll try it on my Mac tomorrow, maybe that makes a difference

**Comment by robintw** [comment]
That's _really_ weird... Out of interest, is this Python 2 or 3? Might be worth trying on both.

**Comment by jvdzwaan** [comment]
It's Python2. I was having troubles installing python3 (in a virtual environment on Ubuntu).
But if I understand correctly, in python3 you can read utf-8 encoded files with standard open, so there is less need to patch codecs there.

**Comment by jvdzwaan** [comment]
Okay, I added example scripts and a Dockerfile for testing in a clean environment, and the errors still occur. (Also on my Mac by the way.)

In python 3 there are no errors, of course...

**Comment by robintw** [comment]
Do these problems still exist?

**Comment by jvdzwaan** [comment]
Probably. My solution was to make a workaround (`recipy.open`; see also #44).

**Comment by robintw** [comment]
Thought so - I'll close this, and if there are any further problems reported then we can open other issues.
