### ISSUE TITLE
sre_constants.error: incomplete escape \U at position 2

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#126]
Under Windows `recipy search file-import.csv` raises `sre_constants.error: incomplete escape \U at position 2` using Git Bash and Anaconda Python prompts:

```
$ recipy search file-import.csv
Traceback (most recent call last):
  File "C:\Users\mjj\Anaconda3\Scripts\recipy-script.py", line 9, in <module>
    load_entry_point('recipy==0.2.3', 'console_scripts', 'recipy')()
  File "C:\Users\mjj\Anaconda3\lib\site-packages\recipy-0.2.3-py3.5.egg\recipyCmd\recipycmd.py", line 116, in main
    search(args)
  File "C:\Users\mjj\Anaconda3\lib\site-packages\recipy-0.2.3-py3.5.egg\recipyCmd\recipycmd.py", line 255, in search
    lambda x: listsearch(os.path.abspath(filename), x)))
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\database.py", line 407,
in search
    elements = [element for element in self.all() if cond(element)]
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\database.py", line 407,
in <listcomp>
    elements = [element for element in self.all() if cond(element)]
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\queries.py", line 45, in __call__
    return self.test(value)
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\queries.py", line 136, in impl
    return test(value)
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\queries.py", line 305, in <lambda>
    return self._generate_test(lambda value: _cmp(value),
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\queries.py", line 299, in _cmp
    return is_sequence(value) and any(cond(e) for e in value)
  File "C:\Users\mjj\Anaconda3\lib\site-packages\tinydb\queries.py", line 299, in <genexpr>
    return is_sequence(value) and any(cond(e) for e in value)
  File "C:\Users\mjj\Anaconda3\lib\site-packages\recipy-0.2.3-py3.5.egg\recipyCmd\recipycmd.py", line 255, in <lambda>
    lambda x: listsearch(os.path.abspath(filename), x)))
  File "C:\Users\mjj\Anaconda3\lib\site-packages\recipy-0.2.3-py3.5.egg\recipyCommon\tinydb_utils.py", line 45, in listsearch
    return bool(re.search(query, item) or
  File "C:\Users\mjj\Anaconda3\lib\re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\mjj\Anaconda3\lib\re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\mjj\Anaconda3\lib\sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\mjj\Anaconda3\lib\sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "C:\Users\mjj\Anaconda3\lib\sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "C:\Users\mjj\Anaconda3\lib\sre_parse.py", line 524, in _parse
    code = _escape(source, this, state)
  File "C:\Users\mjj\Anaconda3\lib\sre_parse.py", line 388, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
sre_constants.error: incomplete escape \U at position 2
```

via @mikej888

**Comment by robintw** [comment]
I'll try and investigate this on my Windows machine at university. @mikej888 - do you know if this was with Python 2 or Python 3? And did the error occur for _all_ file searches? Or just this particular one?

**Comment by mikej888** [comment]
It was for Python 3 and I tried it on other file names e.g. tmp.txt and tmp.csv. I just tried on Windows 7 with Python 2 and it does not throw an exception but returns no results:

```
$ python --version
Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
$ python run_numpy.py
recipy run inserted, with ID f9f390c7-d544-499c-a2e7-2054d4b5bcce
$ recipy latest
Run ID: f9f390c7-d544-499c-a2e7-2054d4b5bcce
Created by mjj on 2016-09-12 11:02:36 UTC
Ran C:\Users\mjj\Desktop\run_numpy.py using C:\Users\mjj\Anaconda2\python.exe
Environment: Windows-7-6.1.7601-SP1, python 2.7.12 |Anaconda 4.1.1 (64-bit)| (
fault, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Inputs:
  C:\Users\mjj\Desktop\tmp.txt
Outputs:
  C:\Users\mjj\Desktop\tmp.csv
  C:\Users\mjj\Desktop\tmp.txt

$ recipy search tmp.txt
No results found

$ recipy search tmp.csv
No results found

$ recipy search run_numpy.py
No results found

$ recipy search -i f9f390c7-d544-499c-a2e7-2054d4b5bcce
No results found
```

**Comment by robintw** [comment]
I've done lots of changes to how the command-line interface works today, and I think this may have been fixed in the process. Partly this was down to ambiguity in exactly what the command-line interface searches: now it defaults to hashes (which are computed and stored by default - the command-line option now turns them _off_) and to search based on file names you have to use `--filepath` (or `-p`).

Can you see if this is now fixed in the latest master?

**Comment by mikej888** [comment]
The following now worked on Windows 7 Enterprise SP1 under Anaconda 4.1.1 Python 2.7.12 and Python 3.5.2 Anaconda 4.1.1 (64-bit):

```
recipy search -p C:\\Users\\mjj\\Desktop\\tmp.txt
recipy search -p C:/Users/mjj/Desktop/tmp.txt
```

**Comment by robintw** [comment]
Great :-)
