### ISSUE TITLE
Output to JSON with no results found fails with IndexError

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#142]
If no results are found from a search, then the output to JSON fails:

```
Traceback (most recent call last):
  File "E:\Anaconda3\Scripts\recipy-script.py", line 9, in <module>
    load_entry_point('recipy==0.3.0', 'console_scripts', 'recipy')()
  File "E:\Anaconda3\lib\site-packages\recipyCmd\recipycmd.py", line 128, in main
    search(args)
  File "E:\Anaconda3\lib\site-packages\recipyCmd\recipycmd.py", line 326, in search
    search_text(args)
  File "E:\Anaconda3\lib\site-packages\recipyCmd\recipycmd.py", line 356, in search_text
    res_to_output = results[-1]
IndexError: list index out of range
```

**Comment by robintw** [comment]
Fixed by 06d5694
