### ISSUE TITLE
UTF-8 decoding error sometimes occurs...

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#152]
I'm not sure why or exactly when this occurs, but the error is:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/robin/code/recipy/recipy/log.py", line 259, in output_file_diffs
    diff = difflib.unified_diff(open(item['tempfilename']).readlines(),
  File "/Users/robin/anaconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by bilderbuchi** [comment]
Some hints here, maybe: http://stackoverflow.com/questions/27219301/utf-8-codec-cant-decode-byte-0x89

**Comment by robintw** [comment]
This is just the same as #121 (I'd forgotten I'd got file_diff_outputs turned on).
