### ISSUE TITLE
Bug in recipy Subversion components

### ISSUE THREAD

**Issue by mikej888** [recipy/recipy#168]
As part of my test framework work I've been working on a branch created from the most recent master commit at that time:

```
commit d9f2bda6fcb6e4d6ac4c45887d98499430124790
Author: Robin Wilson <robin@rtwilson.com>
Date:   Tue Sep 13 16:48:00 2016 +0100

    Updated changelog
```

Now that my work was stable, I merged in the current master branch, the most recent commit of which is

```
commit 5c1600c75c901faa187981052cacfec01efb1011
Merge: 70aa35d 27ca423
Author: Robin Wilson <robin@rtwilson.com>
Date:   Sat Sep 24 13:55:36 2016 +0100

    Merge branch 'decoding-errors'
```

There is a bug in the master branch. If I run:

```
$ python run_numpy.py  in.csv out.csv
```

I get

```
Traceback (most recent call last):
  File "run_numpy.py", line 7, in <module>
    import recipy
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\recipy-0.3.0-py3.5.egg\recipy\__init__.py", line 12, in <module>
    log_init()
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\recipy-0.3.0-py3.5.egg\recipy\log.py", line 81, in log_init
    add_svn_info(run, scriptpath)
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\recipy-0.3.0-py3.5.egg\recipyCommon\version_control.py", line 78, in add_svn_info
    svn_info = svn_client.info()
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\svn\common.py", line 117, in info
    combine=True)
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\svn\common.py", line 70, in run_command
    p.returncode, cmd, stdout))
svn.common.SvnException: Command failed with (1): ['svn', '--non-interactive', 'info', '--xml', 'c:\\Users\\mjj\\Local Documents\\recipy\\tmp\\run_numpy.py']
b'<?xml version="1.0" encoding="UTF-8"?>\r\n<info>\r\nsvn: E155007: \'C:\\Users\\mjj\\Local Documents\\recipy\\tmp\\run_numpy.py\' is not a working copy\r\n'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\recipy-0.3.0-py3.5.egg\recipy\log.py", line 287, in hash_outputs
    run = db.get(eid=RUN_ID)
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\tinydb-3.2.1-py3.5.egg\tinydb\database.py", line 432, in get
TypeError: unhashable type: 'dict'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\recipy-0.3.0-py3.5.egg\recipy\log.py", line 276, in log_exit
    db.update({'exit_date': exit_date}, eids=[RUN_ID])
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\tinydb-3.2.1-py3.5.egg\tinydb\database.py", line 382, in update
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\tinydb-3.2.1-py3.5.egg\tinydb\database.py", line 235, in process_elements
  File "c:\Users\mjj\AppData\Local\Continuum\Anaconda3\lib\site-packages\tinydb-3.2.1-py3.5.egg\tinydb\database.py", line 381, in <lambda>
TypeError: unhashable type: 'dict'
```

This arises in both my TravisCI test environment and Anaconda 3 on Windows. It does not arise under Anaconda 2 or 3 on Ubuntu. My Ubuntu platform differs from the other two in that it does not have Subversion installed.

**Comment by robintw** [comment]
This looks like it was fixed back in Jan 2017 - and the tests are passing now. Thanks Mike.
