### ISSUE TITLE
No attribute 'datasets' error on using with Sklearn

### ISSUE THREAD

**Issue by theSage21** [recipy/recipy#170]
Causes `AttributeError: module 'sklearn' has no attribute 'datasets'` when used with sklearn.  
Can be reproduced with:
```python
import recipy
import sklearn
```

Archlinux, python 3.5, recipy==0.3.0, scikit-learn==0.18.1

**Comment by chiffa** [comment]
Same thing here, here is the full error trace: 

"""
Traceback (most recent call last):
  File "C:/Users/Andrei/PycharmProjects/Pharmacosensitivity_growth_assays-2/src/post_processing.py", line 6, in <module>
    from chiffatools.linalg_routines import gini_coeff
  File "C:\Anaconda2\lib\site-packages\chiffatools\linalg_routines.py", line 11, in <module>
    from sklearn.cluster import spectral_clustering
  File "C:\Anaconda2\lib\site-packages\recipy\PatchImporter.py", line 52, in load_module
    mod = self.patch(mod)
  File "C:\Anaconda2\lib\site-packages\recipy\PatchSimple.py", line 25, in patch
    patch_function(mod, f, self.input_wrapper)
  File "C:\Anaconda2\lib\site-packages\recipyCommon\utils.py", line 82, in patch_function
    setattr(mod, old_f_name, recursive_getattr(mod, function))
  File "C:\Anaconda2\lib\site-packages\recipyCommon\utils.py", line 54, in recursive_getattr
    prev_part = getattr(prev_part, part)
AttributeError: 'module' object has no attribute 'datasets'
"""

**Comment by chiffa** [comment]
upon closer examination it seems to be due to the fact that unless `import sklearn.datasets` was called, `sklearn` does not have the module `datasets` loaded.

```
>>> import sklearn
>>> dir(sklearn)
['__SKLEARN_SETUP__', '__all__', '__builtins__', '__check_build', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'base', 'clone', 'externals', 're', 'setup_module', 'sys', 'utils', 'warnings']
```

It only loads it in case when dataset was explicitely loaded:

```
>>> from sklearn import datasets
>>> dir(sklearn)
['__SKLEARN_SETUP__', '__all__', '__builtins__', '__check_build', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'base', 'clone', 'datasets', 'externals', 'feature_extraction', 'preprocessing', 're', 'setup_module', 'sys', 'utils', 'warnings']
```

**Comment by chiffa** [comment]
A more advanced solution would be to redisign the hooks for patching, but I have no idea how to do it right now. Here is the [Stackoverflow thread ](http://stackoverflow.com/questions/42077673/python-submodule-loading-detection) on the topoc of best doing it. 

The patch #172 should now be resolving this issue as well.

**Comment by robintw** [comment]
Thanks. I'm aware that there are some issues with the patching, and am part-way through solving them. For the moment we'll stop patching sklearn, and I will work on the general improvement to the patching as soon as I'm able to.
