### ISSUE TITLE
Bug with from scipy import stats

### ISSUE THREAD

**Issue by ritviksahajpal** [recipy/recipy#90]
The foll. works fine:
from scipy import stats

However, if I import recipy before from scipy import stats, then I get foll. error:

Traceback (most recent call last):
  File "C:/Users/ritvik/Documents/compute_Percentiles.py", line 2, in <module>
    from scipy import stats
  File "C:\Anaconda64\lib\site-packages\scipy\stats\__init__.py", line 321, in <module>
    from .stats import *
  File "C:\Anaconda64\lib\site-packages\scipy\stats\stats.py", line 184, in <module>
    from . import distributions
  File "C:\Anaconda64\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "C:\Anaconda64\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer
  File "C:\Anaconda64\lib\site-packages\scipy\misc\__init__.py", line 60, in <module>
    from .pilutil import *
  File "C:\Anaconda64\lib\site-packages\scipy\misc\pilutil.py", line 19, in <module>
    from PIL import Image, ImageFilter
  File "C:\Anaconda64\lib\site-packages\recipy\PatchImporter.py", line 52, in load_module
    mod = self.patch(mod)
  File "C:\Anaconda64\lib\site-packages\recipy\PatchSimple.py", line 27, in patch
    patch_function(mod, f, self.input_wrapper)
  File "C:\Anaconda64\lib\site-packages\recipyCommon\utils.py", line 41, in patch_function
    setattr(mod, old_f_name, recursive_getattr(mod, function))
  File "C:\Anaconda64\lib\site-packages\recipyCommon\utils.py", line 27, in recursive_getattr
    prev_part = getattr(prev_part, part)
AttributeError: 'module' object has no attribute 'Image'

**Comment by robintw** [comment]
This is related to #52, and should be fixed by fixing that.
